package com.behosoft.edi.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2016-11-24T18:25:06.722+08:00
 * Generated source version: 2.7.7
 */
@WebService(targetNamespace = "http://service.ws.edi.behosoft.com/", name = "IEdiService")
@XmlSeeAlso({ObjectFactory.class})
public interface IEdiService {

    @WebMethod
    @RequestWrapper(localName = "ediService", targetNamespace = "http://service.ws.edi.behosoft.com/", className = "com.behosoft.edi.ws.service.EdiService")
    @ResponseWrapper(localName = "ediServiceResponse", targetNamespace = "http://service.ws.edi.behosoft.com/", className = "com.behosoft.edi.ws.service.EdiServiceResponse")
    @WebResult(name = "responseData", targetNamespace = "")
    java.lang.String ediService(
            @WebParam(name = "reqData", targetNamespace = "")
                    java.lang.String reqData
    );
}
